name: S3 sync job

concurrency:
  group: ${{ github.head_ref || github.ref_name }} 

on:  
  push:
    tags-ignore:
      - '*'
    branches:
      - 'main'
    paths:
      - 'html/**'
      - '.github/workflows/s3sync.yaml'

permissions:
  id-token: write
  contents: read

jobs:
  s3_sync :
    runs-on: ubuntu-22.04
    steps:
      - name: Verify account number presence
        env:
          AWS_ACCOUNT_NUMBER : ${{ secrets.AWS_ACCOUNT_NUMBER }}
        if: "${{ env.AWS_ACCOUNT_NUMBER!= '' }}"     
        run: echo "This command is executed if AWS_ACCOUNT_NUMBER secret is populated"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/GithubOidcRole
          role-session-name: GitHubActions-${{ github.run_id }}
          aws-region: eu-west-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./html s3://${{ secrets.BUCKET_NAME }} --delete

      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRO_ID }} --paths "/*"